version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1 # Since I run single broker for this example, no change needed unless I scale Kafka to multiple brokers
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Kafka needs Zookeper to manage metadata
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT # Ideal for local development
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Critical for outside-of-Docker communication, as my Spring app
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1